config/routes.rb
Rails.application.routes.draw do
  resources :quotes, only: [:index, :show, :new, :create]

  # You can have the root of your site routed with "root"
  root 'quotes#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/quote.rb
class Quote < ActiveRecord::Base

  ## Validations
  validates :content, presence: true, length: { minimum: 10, maximum: 1000}

  ## Scopes

  scope :published, -> { where(published: true) }

  ## Class methods

  def self.random
    self.published.limit(1).order("RAND()")
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    @quote = Quote.random
  end

  def show
    @quote = Quote.published.find params[:id]
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new quote_params
    @quote.published = false

    if @quote.save
      redirect_to root_path, notice: 'Zgłoszenie przesłane do weryfikacji. Dziękujemy!'
    else
      flash.now[:error] = 'Sprawdź poprawność formularza i spróbuj ponownie!'
      render action: 'new'
    end
  end

  private

    def quote_params
      params.require(:quote).permit(:content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %title<= content_for?(:title) ? "#{yield(:title).chop} - Arystokracja IT" : "Arystokracja IT - Śmietanka ofert pracy branży IT"
    %meta{name: "description", content: content_for?(:description) ? "#{yield(:description)}" : "Wybrane cytaty z ofert pracy branży IT! Mamy najlepsze oferty, benefity, płace, wszystko!" }

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true

    - if content_for(:og)
      = yield :og
    - else
      %meta{property: "og:title", content: "Arystokracja IT - Śmietanka ofert pracy branży IT"}
      %meta{property: "og:description", content: "Arystokracja IT to Wybrane cytaty z ofert pracy branży IT! Mamy najlepsze oferty, benefity, płace, wszystko!"}
      %meta{property: "og:url", content: root_url}
      %meta{property: "og:site_name", content: "ArystokracjaIT.pl"}
      %meta{property: "og:image", content: asset_url('og.png')}
    %meta{property: "og:image", content: asset_url('og.png')}
    %meta{property: "fb:app_id", content: "727774573991183"}

    = csrf_meta_tags

    %link{rel: 'shortcut icon', href: 'favicon.png'}
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body
    = render partial: 'layouts/shared/header'
    = render partial: 'layouts/shared/flash'

    %div.ait-wrapper
      = yield
    - if Rails.env == "production"
      = render partial: 'layouts/shared/gat'

app/views/layouts/shared/_flash.html.haml
- flash.each do |name, msg|
  %div{class: "ait-flash ait-flash--#{name}"}
    %div.ait-flash__message=msg

app/views/layouts/shared/_header.html.haml
%header.ait-header
  %h1.ait-header__logo
    = link_to root_path, class: 'ait-header__logo-link' do
      Arystokracja IT
      %sup.ait-header__version
        beta
  = link_to "Dodaj propozycję", new_quote_path, class: 'ait-header__link'

app/views/quotes/_quote.html.haml
%div.ait-quote
  %div.ait-quote__intro
    /= raw "Arystokracja IT to #{link_to 'bonusy za polecenia', '#'}:"
    Arystokracja IT to:
  %div.ait-quote__content
    = simple_format quote.content
  %div.ait-quote__meta
    = link_to quote.created_at, quote, class: 'ait-quote__permalink'

app/views/quotes/index.html.haml
= render @quote

app/views/quotes/new.html.haml
= form_for @quote, html: {class: 'ait-form'} do |f|

  %div.ait-form__row
    = f.label :content, "Czym jest Arystokracja IT:", class: 'ait-form__label'
    = f.text_area :content, class: 'ait-form__textarea', autofocus: true

  %div.ait-form__actions
    = f.submit "Wyślij propozycję", class: 'ait-form__submit-button'

app/views/quotes/show.html.haml
= render @quote

- content_for :og do
  %meta{property: "og:title", content: "ArystokracjaIT to"}
  %meta{property: "og:description", content: truncate(strip_tags(@quote.content), length: 150)}
  %meta{property: "og:url", content: quote_url(@quote)}
  %meta{property: "og:site_name", content: "ArystokracjaIT.pl"}
  %meta{property: "og:type", content: "article"}